# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "json"

gem "sendgrid-ruby", "~> 6.0"

gem "colorize", "~> 0.8.1"

gem "rubyjokes", "~> 1.0"

gem "test-unit", "~> 3.3"
